# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wazoooom!' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'SDWebImage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  # Pods for Wazoooom!

end
